@localhost = http://localhost:5146

GET {{localhost}}/openapi/v1.json
###

GET {{localhost}}/api/games/
Accept: application/json
###

GET {{localhost}}/api/games/{{id}}
Accept: application/json
###

POST {{localhost}}/api/games/
Content-Type: application/json

{
  "platform": "Steam",
  "released": "2025-10-12",
  "title": "League of Legends"
}
###

PUT {{localhost}}/api/games/{{id}}
Content-Type: application/json

{
  "platform": "GOG",
  "released": "9999-10-12",
  "title": "Edited Title"
}
###
