@GameDashboard_HostAddress = http://localhost:5146

GET {{GameDashboard_HostAddress}}/weatherforecast/
Accept: application/json
###

GET {{GameDashboard_HostAddress}}/api/games/
Accept: application/json
###

GET {{GameDashboard_HostAddress}}/api/games/{{id}}
Accept: application/json
###

POST {{GameDashboard_HostAddress}}/api/games
Accept: application/json
